{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c0f89395-8c3b-47d5-9bfc-399acd2e265e",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import numpy as np\n",
    "import MDAnalysis as mda\n",
    "from tqdm import tqdm\n",
    "\n",
    "# --- CONFIGURATION ---\n",
    "BASE_PATH = \"/home/twlodarski/Projects/ribosome_tunnels/\"\n",
    "\n",
    "# 1. Organism Dictionaries\n",
    "bacteria_dict = {\n",
    "    'abau': 'A.baumannii', 'bbur': 'B.burgdorferi', 'bsub': 'B.subtilis',\n",
    "    'drad': 'D.radiodurans', 'ecoli': 'E.coli', 'efae': 'E.faecalis',\n",
    "    'fjoh': 'F.johnsoniae', 'linn': 'L.innocua', 'llac': 'L.lactis',\n",
    "    'lmon': 'L.monocytogenes', 'mpne': 'M.pneumoniae', 'msme': 'M.smegmatis',\n",
    "    'mtub': 'M.tuberculosis', 'paer': 'P.aeruginosa', 'pgin': 'P.gingivalis',\n",
    "    'pura': 'P.urativorans', 'saur': 'S.aureus', 'sfra': 'S.fradiae',\n",
    "    'tthe': 'T.thermophilus', 'vnat': 'V.natrigens'\n",
    "}\n",
    "\n",
    "archaea_dict = {\n",
    "    'hmar': 'H.marismorturi', 'mace': 'M.acetivorans', 'pfur': 'P.furiosus', \n",
    "    'saci': 'S.acidocaldarius', 'tkod': 'T.kodakarensis', 'pcal': 'P.calidifontis'\n",
    "}\n",
    "\n",
    "eukaryota_dict = {\n",
    "    'atha': 'A.thaliana', 'calb': 'C.albicans', 'cele': 'C.elegans',\n",
    "    'cpor': 'C.porcellus', 'cser': 'C.sericeus', 'cthe': 'C.thermophilia',\n",
    "    'dmel': 'D.melanogaster', 'drer': 'D.rerio', 'ecun': 'E.cuniculi',\n",
    "    'egra': 'E.gracilis', 'ehis': 'E.histolytica',\n",
    "    'ggal': 'G.gallus', 'glam': 'G.lamblia', 'hgla': 'H.glaber',\n",
    "    'hsap': 'H.sapiens', 'klac': 'K.lactis', 'ldon': 'L.donovani',\n",
    "    'lmaj': 'L.major', 'mmus': 'M.musculus', 'ncra': 'N.crasa',\n",
    "    'ntab': 'N.tabacum', 'ocun': 'O.cuniculus', 'pfal': 'P.falciparum',\n",
    "    'ploc': 'P.locustae', 'rnor': 'R.norvegicus', 'scer': 'S.cerevisiae',\n",
    "    'slop': 'S.lophii', 'slyc': 'S.lycoperscium', 'spom': 'S.pombe',\n",
    "    'sscr': 'S.scrofa', 'taes': 'T.aestivum', 'tbru': 'T.brucei',\n",
    "    'tcru': 'T.cruzi', 'tgon': 'T.gondii', 'tthe': 'T.thermophila',\n",
    "    'tvag': 'T.vaginalis', 'vnec': 'V.necatrix', 'xlae': 'X.laevis'\n",
    "}\n",
    "\n",
    "# 2. Map domains to their respective keys and topology types\n",
    "DOMAINS = {\n",
    "    \"bacteria\":  {\"ids\": list(bacteria_dict.keys()),  \"top_prefix\": \"NC_FME\"},\n",
    "    \"eukaryota\": {\"ids\": list(eukaryota_dict.keys()), \"top_prefix\": \"NC_MET\"},\n",
    "    \"archaea\":   {\"ids\": list(archaea_dict.keys()),   \"top_prefix\": \"NC_MET\"},\n",
    "    \"mito\":      {\"ids\": ['atha','crei','hsap','lmaj','ncra','pmag','scer','tthe'], \"top_prefix\": \"NC_FME\"}\n",
    "}\n",
    "\n",
    "ITEMS = [\"10\", \"20\", \"30\", \"40\", \"60\"]\n",
    "\n",
    "# Since names are standardized, we just define the three relative paths once\n",
    "TRAJECTORIES = [\"fitted.xtc\", \"ref_1/fitted.xtc\", \"ref_2/fitted.xtc\"]\n",
    "\n",
    "# ---------------------\n",
    "\n",
    "global_min_dim = {}\n",
    "global_max_dim = {}\n",
    "\n",
    "print(\"Calculating global bounding boxes...\")\n",
    "\n",
    "for item in tqdm(ITEMS, desc=\"Lengths\"):\n",
    "    item_min = np.array([np.inf, np.inf, np.inf])\n",
    "    item_max = np.array([-np.inf, -np.inf, -np.inf])\n",
    "    for domain_name, config in DOMAINS.items():\n",
    "        if domain_name == \"mito\" and item == \"60\":\n",
    "            continue\n",
    "        for org_id in config[\"ids\"]:\n",
    "            work_dir = os.path.join(BASE_PATH, domain_name, org_id, item)\n",
    "            topology_file = os.path.join(work_dir, f\"{config['top_prefix']}_{item}.pdb\")\n",
    "            if not os.path.exists(topology_file):\n",
    "                tqdm.write(f\"⚠️ Missing topology: {topology_file}. Skipping.\")\n",
    "                continue\n",
    "            # Standardized trajectory loop\n",
    "            for traj_name in TRAJECTORIES:\n",
    "                trajectory_file = os.path.join(work_dir, traj_name)\n",
    "                if not os.path.exists(trajectory_file):\n",
    "                    continue\n",
    "                try:\n",
    "                    u = mda.Universe(topology_file, trajectory_file)\n",
    "                    for ts in u.trajectory:\n",
    "                        positions = u.atoms.positions\n",
    "                        item_min = np.minimum(item_min, positions.min(axis=0))\n",
    "                        item_max = np.maximum(item_max, positions.max(axis=0))\n",
    "                except Exception as e:\n",
    "                    tqdm.write(f\"❌ Error loading {trajectory_file}: {e}\")\n",
    "    global_min_dim[item] = item_min\n",
    "    global_max_dim[item] = item_max\n",
    "\n",
    "# Write results\n",
    "out_file = os.path.join(BASE_PATH, \"grid_data.dat\")\n",
    "with open(out_file, \"w\") as f:\n",
    "    for key in ITEMS:\n",
    "        if key in global_min_dim:\n",
    "            min_str = ' '.join(f\"{x:.3f}\" for x in global_min_dim[key])\n",
    "            max_str = ' '.join(f\"{x:.3f}\" for x in global_max_dim[key])\n",
    "            f.write(f\"{key} {min_str}\\n\")\n",
    "            f.write(f\"{key} {max_str}\\n\")\n",
    "\n",
    "print(f\"\\n✅ Grid bounding boxes saved to {out_file}\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
